services:
  postgres:
    image: postgres:16-alpine
    container_name: postgres_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${ROOT_USER}
      POSTGRES_PASSWORD: ${ROOT_USER_PASSWORD}
      POSTGRES_DB: finance-wallet-db
    ports:
      - "${HOST_PORT}:${CONTAINER_PORT}"
    volumes:
      - postgres_db_volume:/var/lib/postgresql/data
volumes:
  postgres_db_volume:
